# Generated by Django 5.0.6 on 2024-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playerModel',
            fields=[
                ('player', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('squad', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('fulltimeplayed', models.FloatField()),
                ('goals', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('sot', models.IntegerField()),
                ('sotpercent', models.FloatField()),
                ('shotspernintey', models.FloatField()),
                ('sotpernintey', models.FloatField()),
                ('goalpershot', models.FloatField()),
                ('goalspersot', models.FloatField()),
                ('shotdistance', models.FloatField()),
                ('xg', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'playerstats',
                'managed': False,
            },
        ),
    ]
